name: meta
version: 1.3.0-nullsafety
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/meta
description: >
 This library contains the declarations of annotations that developers can use
 to express the intentions that otherwise can't be deduced by statically
 analyzing the source code. These annotations are intended to be used by tools
 to provide a better user experience.
environment:
  # This must remain a tight constraint (only allow dev versions) until nnbd is
  # stable.
  sdk: '>=2.9.0-18.0 <2.9.0'
